### ISSUE TITLE
How do I specify a HashMap in yml?

### ISSUE THREAD

**Issue by justin-jalandoni** [yaml/yaml#59]
Hello, I am specifying the structure of my object using yml. I would like to ask how can we specify a Java HashMap in yml.
Here is my yml file:

```
## This describes the Structure of an object represented by this class.
---
$schema: http://json-schema.org/draft-06/schema#
title: default object
description: this is a description of this object
type: object
properties:
  notes:
    type: string
  number:
    type: string
  loc:
    type: object
    properties:
      long:
        type: number
      lat:
        type: number
    required:
      - long
      - lat
    additionalProperties: false
  mymap:
    # what to place here
required:
  - notes
  - number
  - loc
  - mymap
additionalProperties: false
```
